[package]
name = "signatures"
version = "0.1.0"
authors = ["BohuTANG <overred.shuttler@gmail.com>"]
license = "BSD"
publish = false
edition = "2018"

[dependencies]
curves= {path = "../curves"}
subgroups= {path = "../subgroups"}
algebra= {path = "../algebra"}